### PR TITLE
Update fish shell completions to match new cli interface

### PR DESCRIPTION
**Pull request by zph**
Hello @toumorokoshi !

When tome moved away from --complete style arguments it broke commandline completions for fish.

This patch resolves the issue and re-enables commandline completion.

Note: I'm putting this up as draft so that I can test drive it a few days before being confident in its correctness.

### CODE REVIEW

**Review by toumorokoshi — APPROVED** [review]
Thanks! I'll try to make sure to test for fish in the future - sorry about that.

**Comment by toumorokoshi** [comment]
also ack on this being a draft - give me a ping when you feel it's ready.

**Comment by toumorokoshi** [comment]
@zph how is it working?

**Comment by zph** [comment]
Great thanks :)

I adopted tome to help with team level cli tooling and it's been going well. Thanks for building this project and welcoming contributions for it.

**Pull request merged**
